# fly.toml app configuration file generated for divine-resonance-4795 on 2023-10-03T22:20:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-resonance-4795"
primary_region = "bos"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
